spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: codecool
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true
    databaseplatform: org.hibernate.dialect.H2Dialect

app:
  tokenSecret: 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
  tokenExpirationMsec: 864000000
  authorizedRedirectUris:
    - http://localhost:3000/oauth2/redirect
